{
 "title": "Mod Security",
 "time": { "from": "2024-01-06T10:37:17.744Z", "to": "2024-01-06T22:37:17.744Z" },
 "panels": [
  {
   "title": "Attacks per Attacker IP",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_ip) (count_over_time({compose_service=\"nginx\"} != \"nginxmainlog\" | json client_ip=\"transaction.client_ip\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Attacks per uri",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (uri, count) (count_over_time({compose_service=\"nginx\"} != \"nginxmainlog\" | json uri=\"transaction.request.uri\" |  uri != \"\" | __error__=\"\" [$__range]))\r\n"
    }
   ]
  },
  {
   "title": "Today Detected Attacks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({compose_service=\"nginx\"} != \"nginxmainlog\"  |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Today Total requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({compose_service=\"nginx\"} |= \"nginxmainlog\"  |= `` [$__auto]))"
    }
   ]
  },
  {
   "title": "Attackers location",
   "type": "geomap",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (count_over_time({compose_service=\"nginx\"} != \"nginxmainlog\" | json uri=\"transaction.request.uri\" |  __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Volumne Nginx",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"nginx\"} |= \"nginxmainlog\" [$__auto])"
    }
   ]
  },
  {
   "title": "ModSec  Logs Volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"nginx\"} != \"nginxmainlog\" [$__auto])"
    }
   ]
  },
  {
   "title": "Nginx Access Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} | json \r\n| __error__=`` \r\n| line_format \" {{.status}} {{.client_ip}} {{.url}} {{.request_method}} {{.protocol}}\""
    }
   ]
  },
  {
   "title": "Detected Attacks Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"} \r\n!= \"nginxmainlog\" \r\n|= \"error\" \r\n| json messages=\"transaction.messages[0].message\",  uri=\"transaction.request.uri\", rule_id =\"transaction.messages[0].details.ruleId\", data =\"transaction.messages[0].details.data\", client_ip=\"transaction.client_ip\" | line_format \"Attacker -> {{.client_ip}}  || Details -> {{.messages}} || Rule ID -> {{.rule_id}} uri -> {{.uri}} \\n More info -> {{.data}} \" "
    }
   ]
  }
 ]
}