version: '3'

services:
  nginx:
    container_name: secopsdeploynginx
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
      - grafana
    volumes:
      - "./conf/modsec/:/etc/nginx/modsec/"
      - "./conf/conf.d/:/etc/nginx/conf.d/"
    networks:
      - monitoring
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=nginx


  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    depends_on:
      - nginx
    volumes:
    - ./loki/local.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - node_exporter_data:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    depends_on:
      - node_exporter
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    user: root
    volumes:
      - /var/log:/var/log
      - /var/log/system.log:/var/log/root/system.log
      - ./port/local.yml:/etc/config/promtail-local-config.yml
    entrypoint:
      - /usr/bin/promtail
      - -config.file=/etc/config/promtail-local-config.yml
    ports:
      - "9080:9080"
    networks:
      - monitoring

  grafana:
    image:  grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SECURITY_ADMIN_USER=admin123
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  nginx_data:
  loki_data:
  node_exporter_data:
  grafana_data:
